### PR TITLE
Rename fromFunction to lift

### PR DESCRIPTION
**Pull request by tampler**
Following pioneering works of Hughes and Paterson on Arrows and Haskell impl, I renamed `fromFunction` into `lift` to deliver more sense and avoid much typing

### CODE REVIEW

**Comment by adamgfraser** [comment]
I would suggest we keep `fromFunction` for consistency with other ZIO libraries but we could also add an alias for it. One thing we should think about is how we want to use the `apply` method. I kind of think it should lift a `A => IO[E, B]` into a `ZArrow` because in practice I think people are going to want to lift effectual functions more often than pure ones but I'm not sure.

**Comment by tampler** [comment]
Added `fromFunction` and `fromFunctionF` aliases. Still believe they are verbose and dummy and need to be removed from all ZIO projects

**Comment by adamgfraser** [comment]
Looks like the laws stuff is in this branch too? Shall we handle that as part of the other PR? What do you think about using `apply` instead of `liftM` so you could just do `ZArrow(???)`?

**Comment by tampler** [comment]
I'll remove Laws stuff from here.
As for `apply` vs `liftF`, I'll add both. Conceptually, `liftF` is a big idea, while `apply` is just a Scala specific stuff. I'd like to separate big ideas from coding mechanics, so would like to preserve `liftM` as it's already implemented

**Comment by tampler** [comment]
@adamgfraser Added apply

**Pull request merged**
